image: docker:latest
services:
- docker:dind

docker_image:
  stage: build
  script:
  - export VERSION=$(cat version.txt)
  - echo "Building image version ${VERSION}."
  - echo "Project path ${CI_PROJECT_PATH}"
  - docker build --build-arg "VERSION=${VERSION}" -t "${CI_PROJECT_NAME}:${VERSION}" .
  tags:
  - shared
  - linux
  - docker

push_gitlab:
  stage: deploy
  script:
  - export VERSION=$(cat version.txt)
  - docker tag "${CI_PROJECT_NAME}:${VERSION}" "registry.gitlab.com/${CI_PROJECT_PATH}:${VERSION}"
  - docker push "registry.gitlab.com/${CI_PROJECT_PATH}:${VERSION}"
